/**:
    ros__parameters:
        general:
            camera_name: 'zed'
        mapping:
            mapping_enabled: true
        pos_tracking:
            publish_tf: false
            publish_map_tf: false
